# Use Ballerina Swan Lake image
FROM ballerina/ballerina:2201.7.2

# Copy the service files
COPY . /client

# Set the work directory
WORKDIR /client

# Build the service
RUN bal build --skip-tests client

# Expose the application port (optional)
EXPOSE 8084

# Run the service
CMD ["bal", "run", "client"]
