version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    container_name: zookeeper

  kafka1:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka1:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
    depends_on:
      - zookeeper
    container_name: kafka1

  kafka2:
    image: wurstmeister/kafka
    ports:
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka2:9094,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9094,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
    depends_on:
      - zookeeper
    container_name: kafka2

  kafka3:
    image: wurstmeister/kafka
    ports:
      - "9094:9094"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka3:9095,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9095,OUTSIDE://0.0.0.0:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 3
    depends_on:
      - zookeeper
    container_name: kafka3

  kafka4:
    image: wurstmeister/kafka
    ports:
      - "9095:9095"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka4:9096,OUTSIDE://localhost:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9096,OUTSIDE://0.0.0.0:9095
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 4
    depends_on:
      - zookeeper
    container_name: kafka4

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    container_name: mongodb

  central-logistics-service:
    build: ./central-logistics-service
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - kafka1
      - kafka2
      - kafka3
      - kafka4
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka1:9093,kafka2:9094,kafka3:9095,kafka4:9096"
      MONGODB_URI: "mongodb://mongodb:27017/LogisticSystemDB"
    container_name: central-logistics-service

  standard-delivery-service:
    build: ./standard-delivery-service
    depends_on:
      - mongodb
      - kafka1
      - kafka2
      - kafka3
      - kafka4
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka1:9093,kafka2:9094,kafka3:9095,kafka4:9096"
      MONGODB_URI: "mongodb://mongodb:27017/LogisticSystemDB"
    container_name: standard-delivery-service

  express-delivery-service:
    build: ./express-delivery-service
    depends_on:
      - mongodb
      - kafka1
      - kafka2
      - kafka3
      - kafka4
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka1:9093,kafka2:9094,kafka3:9095,kafka4:9096"
      MONGODB_URI: "mongodb://mongodb:27017/LogisticSystemDB"
    container_name: express-delivery-service

  international-delivery-service:
    build: ./international-delivery-service
    depends_on:
      - mongodb
      - kafka1
      - kafka2
      - kafka3
      - kafka4
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka1:9093,kafka2:9094,kafka3:9095,kafka4:9096"
      MONGODB_URI: "mongodb://mongodb:27017/LogisticSystemDB"
    container_name: international-delivery-service

volumes:
  mongodb_data: