# Use Ballerina Swan Lake image
FROM ballerina/ballerina:2201.10.0

# Copy the service files
COPY . /express-delivery-service

# Set the work directory
WORKDIR /express-delivery-service

# Build the service
RUN bal build --skip-tests express-delivery-service

# Expose the application port (optional)
EXPOSE 8081

# Run the service
CMD ["bal", "run", "express-delivery-service"]
