# Use Ballerina Swan Lake image
FROM ballerina/ballerina:2201.7.2

# Copy the service files
COPY . /international-delivery-service

# Set the work directory
WORKDIR /international-delivery-service

# Build the service
RUN bal build --skip-tests international-delivery-service

# Expose the application port (optional)
EXPOSE 8082

# Run the service
CMD ["bal", "run", "international-delivery-service"]
